environment:

  matrix:

    - PYTHON: "C:\\Miniconda36-x64"
      PYTHON_VERSION: "3.6.x"
      PYTHON_ARCH: "64"
      ENV_NAME: "environment_py3_win.yml"

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "conda update -q --yes conda"
  - "conda env create -f %ENV_NAME% -n parcels"
  - "activate parcels"
  - "python setup.py install"

build: false

test_script:
  - "py.test -v -s tests/"
  - "parcels_get_examples examples/"
  - 'py.test -v -s --nbval-lax examples/ -k "not documentation" '
