name: test-suite
on: [push pull-request]
jobs:
  PytestLinux:
    name: Github Action for testing on Linux
    runs-on: ubuntu-latest
    steps:
    env:
      PY_VERSION=3
      OS_NAME=linux

    - uses: actions/checkout@master
    - name: Install linux
      env: 
        MINICONDA_NAME=Miniconda3-latest-Linux-x86_64.sh
      run: ./.github/scripts/linux_install.sh
    - name: Github Action for testing on Linux
      run: ./.github/scripts/linux_test.sh
